name: main
on:
  push:
    branches: [main, next]
  pull_request:
jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - run: go run lesiw.io/op@latest
  test:
    needs: gate
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: macos-latest
            go: stable
          - runner: macos-latest
            go: oldstable
          - runner: windows-latest
            go: stable
          - runner: windows-latest
            go: oldstable
          - runner: ubuntu-latest
            go: oldstable
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - run: go run lesiw.io/op@latest
  alpine:
    needs: gate
    strategy:
      matrix:
        go: [stable, oldstable]
    runs-on: ubuntu-latest
    container: golang:${{ matrix.go }}-alpine
    steps:
      - run: apk add --no-cache git
      - uses: actions/checkout@v4
      - run: go run lesiw.io/op@latest
  freebsd:
    needs: gate
    strategy:
      matrix:
        go: [stable, oldstable]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          prepare: pkg install -y go
          run: go run lesiw.io/op@latest
